# Generated by Django 3.0.3 on 2021-02-17 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusInfo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('Artist', models.TextField()),
                ('link', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
