# Generated by Django 3.0.3 on 2021-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourMusic', '0002_statusinfo_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusinfo',
            name='cover_image',
            field=models.ImageField(blank=True, default='2.jpg', null=True, upload_to='cover_image'),
        ),
    ]
